### PR TITLE
Make meddler a module

### PR DESCRIPTION
**Pull request by tamoore**
I'm not sure how often we're contributing back to the forked repository, but in general, it would be nice if meddler was now a module so that we could version it easily. 

Furthermore to the above, in my endeavour to support sqlc organizationally, we need to include the `PrepareContext` method in meddler's `DB` interface. The main reason for this is that the interface for `sqlc` matches the meddler interface except for this missing method. I don't think this will have any impact on other codebases that use `meddler` as my understanding is this is ultimately the interface that will be used to make the SQL open connection (to the datastore), and `PrepareContext` is one of the methods it can have defined.

### CODE REVIEW

**Review by lwc — APPROVED** [review]

**Comment by mtibben** [comment]
Alternatively, would it make sense to either
 1. rebase our changes on mainline to avoid further divergence
 2. get our changes into mainline

**Comment by tamoore** [comment]
@mtibben do you mean close this PR and open it on the original repo (https://github.com/russross/meddler)? Just to clarify.

**Comment by mtibben** [comment]
The original repo already is using go modules

**Comment by mtibben** [comment]
so wondering if either rebasing or convergence is a better option

**Comment by tamoore** [comment]
@mtibben yeah that's a fair question, we'd still need to add the `PrepareContext` method on the `DB` interface in `loadsave.go`, but I could look into how feasible a rebase on this forked meddler is.

**Pull request closed without merging**
